# Generated by Django 3.2.2 on 2021-05-17 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.ForeignKey(default='activo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.estado'),
        ),
    ]
