# Generated by Django 3.2.2 on 2021-06-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_alter_usuarios_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(default='usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webApp.rol'),
        ),
    ]
